spring.application.name=userservice


logging.level.org.springframework.security = trace

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/dev_auth_db
#spring.datasource.url=jdbc:mysql://dev-user-db-aws.cnqiiiiqycvg.ap-south-1.rds.amazonaws.com/dev_user_db_rds
#spring.datasource.username=dev_user
#spring.datasource.password=cozurda1
spring.datasource.username=devuser
spring.datasource.password=devpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

server.port=8081


#logging.level.org.springframework.security=debug


